using System.ComponentModel.DataAnnotations;
using TimeMeasurement_Backend.Entities.Constraints;

namespace TimeMeasurement_Backend.Entities
{
    /// <summary>
    /// A simple Race, to be expanded on in the furure
    /// </summary>
    public class Race
    {
        /// <summary>
        /// The date and time in ms since unix epoch
        /// </summary>
        public long Date { get; set; }

        /// <summary>
        /// Generated by entity framework
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Link to the announcement of the race
        /// </summary>
        [IsUrl]
        public string Link { get; set; }

        /// <summary>
        /// The Title of the race
        /// </summary>
        [Required]
        public string Title { get; set; }

        /// <summary>
        /// If this race has been started / completed in the past
        /// </summary>
        public bool Done { get; set; }
    }
}