namespace TimeMeasurement_Backend.Entities
{
    /// <summary>
    /// A simple Race, to be expanded on in the furure
    /// </summary>
    public class Race
    {
        /// <summary>
        /// The date and time in ms since unix epoch
        /// </summary>
        public long Date { get; set; }

        /// <summary>
        /// Generated by entity framework
        /// </summary>
        public int Id { get; set; }
    }
}