using System.ComponentModel.DataAnnotations;
using TimeMeasurement_Backend.Entities.Constraints;

namespace TimeMeasurement_Backend.Entities
{
    /// <summary>
    /// A Race that either took part in the past or will take place in the furture
    /// </summary>
    public class Race
    {
        /// <summary>
        /// The date and time the race takes place, in ms since unix epoch
        /// </summary>
        public long Date { get; set; }

        /// <summary>
        /// Wether this race has been started / completed in the past
        /// </summary>
        public bool Done { get; set; }

        /// <summary>
        /// Unique Identifier,
        /// Generated by entity framework
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Link to the announcement of the race
        /// Has to be a valid URL
        /// </summary>
        [IsUrl]
        public string Link { get; set; }

        /// <summary>
        /// The Title of the race,
        /// required
        /// </summary>
        [Required]
        public string Title { get; set; }
    }
}