namespace TimeMeasurement_Backend.Entities
{
    /// <summary>
    /// Everybody who participated in a race is stored as a runner
    /// </summary>
    public class Runner
    {
        /// <summary>
        /// Generated by entity framework
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The personal data of the runner
        /// </summary>
        public Participant Participant { get; set; }

        /// <summary>
        /// The race the runner participated in
        /// </summary>
        public Race Race { get; set; }

        /// <summary>
        /// The starter number of the runner
        /// </summary>
        public int Starter { get; set; }

        /// <summary>
        /// The time the runner took to complete the race in ms
        /// </summary>
        public long Time { get; set; }
    }
}