namespace TimeMeasurement_Backend.Entities
{
    /// <summary>
    /// An Entity to record when somebody started and finished their run
    /// </summary>
    public class Time
    {
        /// <summary>
        /// The end time of the run
        /// </summary>
        public long? End { get; set; }

        /// <summary>
        /// The ID of the object (generated by EntityFramework)
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// The start time of the run
        /// </summary>
        public long? Start { get; set; }

        /// <summary>
        /// The time between Start and End
        /// </summary>
        public long? Value => End - Start;
    }
}